### ISSUE TITLE
A code review for the my--portfolio repository (Transition and animation of portfolio page)

### ISSUE THREAD

**Issue by dlwub** [frankfembo/my--portfolio#11]
The codes in
https://github.com/frankfembo/my--portfolio/pull/8/commits/10f6e580b7b2bf2dd7f56348872b8235415856a3#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aR692-R702
are taken from the teaching material of Microverse almost directly. I think it would be better for the future to be a little bit creative.

**Comment by megha-n-bodke** [comment]
- Class names are descriptive.
- Suggestion: could have rename image, to be prpoper.

**Comment by AmitKlohan** [comment]
Good Job so far
